### ISSUE TITLE
Multiple Turtles not playing well.

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [apemanzilla/turtlegistics#9]
When multiple turtles are connected to the same turtlegistics network, and you pull from the second one to be turned on, it only pulls the stack to the original turtle.

**Comment by dmarcuse** [comment]
Known issue, no good fix at the current time.

**Comment by incinirate** [comment]
I made some changes (at #16). Thoughts? It's not the cleanest solution, but it does work in my tests.
